### ISSUE TITLE
No module named 'salmetric'

### ISSUE THREAD

**Issue by sofmonk** [Andrew-Qibin/SalMetric#3]
After following installation, 
```
$ python setup.py install
running install
running build
running build_ext
running install_lib
running install_egg_info
Removing /home/as/anaconda3/lib/python3.7/site-packages/salmetric-0.1-py3.7.egg-info
Writing /home/as/anaconda3/lib/python3.7/site-packages/salmetric-0.1-py3.7.egg-info

```
getting following error,

```
$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import salmetric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'salmetric'
```

**Comment by LnSCV** [comment]
Have you solved the problem?I met it ,too.

**Comment by Forest-Xie** [comment]
I have the same problem. And I find something different: after installation, I got a file not a directory in sit-package directory, there is no code, and the generated file containing some message labeled "unknown". unfortunately, I can't fix this, even after I change the file to a directory and copy files under directory 'python' to the directory. Where is the problem?

**Comment by LnSCV** [comment]
> I have the same problem. And I find something different: after installation, I got a file not a directory in sit-package directory, there is no code, and the generated file containing some message labeled "unknown". unfortunately, I can't fix this, even after I change the file to a directory and copy files under directory 'python' to the directory. Where is the problem?

I  haven't solved the problem until now

**Comment by djl0912111** [comment]
I met the same problem. And I haven't solved the problem utiol now.

**Comment by djl0912111** [comment]
> After following installation,
> 
> ```
> $ python setup.py install
> running install
> running build
> running build_ext
> running install_lib
> running install_egg_info
> Removing /home/as/anaconda3/lib/python3.7/site-packages/salmetric-0.1-py3.7.egg-info
> Writing /home/as/anaconda3/lib/python3.7/site-packages/salmetric-0.1-py3.7.egg-info
> ```
> 
> getting following error,
> 
> ```
> $ python
> Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import salmetric
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'salmetric'
> ```

Have you solved this problem?Hope your reply.
